### ISSUE TITLE
Getting prompted for passphrase for each push/pull

### ISSUE THREAD

**Issue by dvdmon** [jjaimealeman/wdb-get-good-with-git#20]
I'm not sure if this is an appropriate "issue" or if it's better handled somewhere else.  I've just trying to push/pull to my forked copy of this repository but keep getting asked for my passphrase.  If I enter it, it works, but I don't want to have to enter it for each push/pull/fetch/etc.  I googled for a solution and saw something about add-ssh -K, but when I do that, I get prompted "Enter PIN for authentication:"  Entering my passphrase there does not work and so I don't know what PIN it's are asking for.  This is using Git Bash on Windows, by the way, if that matters.  Anyone else run into this issue?

**Comment by jjaimealeman** [comment]
@dvdmon 
I haven't used Windows in ages, but I'm thinking it has to do with SSH Authentication.

Have a long at this, seems like a proper solution: https://gist.github.com/bsara/5c4d90db3016814a3d2fe38d314f9c23

I suggest first reading through it and understand what files and folders it's asking you to modify before you do anything, so that if it doesn't work, you can easily delete them.

Let me know if this works for you, so we can add this to the Wiki as a solution for Windows users who join the project :+1:

**Comment by dvdmon** [comment]
@jjaimealeman ok, thanks, after creating files, modifying them a bunch based on some of the comments there, I finally got it working!

**Comment by jjaimealeman** [comment]
@dvdmon 

Awesome, glad it worked out!

- If that gist worked out for you, I can link to it from the Wiki for other Windows users.
- *OR* 
- Would you be able to make a `something.md` file documenting your steps? Instead of linking to an external source, we can keep all the content here to make it easier?! It'll be added to the Wiki and of course you'd get the credit as author.

**Comment by dvdmon** [comment]
Actually, I need to test it again as it seemed to stop working yesterday..

**Comment by jjaimealeman** [comment]
@dvdmon 

Ok. Let me know how that goes?!

Heading back to bed soon for a few more hours 😴

**Comment by jjaimealeman** [comment]
@dvdmon 

Has this been fixed?!

**Comment by dvdmon** [comment]
No, but I think it's something in the config file that I mistyped, I need to look at it still.

**Comment by jjaimealeman** [comment]
@dvdmon 

Okay bud. Let me know how it all works out.

**Comment by dvdmon** [comment]
@jjaimealeman hey, sorry it took a while.  Finally figured out that I'd accidentally added some characters to the .bashrc file that was messing with the script.  After I removed them things are working again.

**Comment by jjaimealeman** [comment]
@dvdmon 

At least you figured it out ;) 

Aaahhh, trouble-shooting, Been doing that all weekend on my OS. 
Can you still work on something for the Wiki to help others with this?!

**Comment by dvdmon** [comment]
@jjaimealeman I can do that, but may not be for a bit as I'm kind of swamped with work right now.

**Comment by jjaimealeman** [comment]
> @jjaimealeman I can do that, but may not be for a bit as I'm kind of swamped with work right now.

@dvdmon 

No worries brother. 👍
